---
title: "airq_report"
author: "Matthew Krogman"
output: pdf_document
font_size: 12pt
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
```

# Abstract



# Introduction

As climate change continues to progress, and the population of major urban and industrial centers, more attention has been given to the quality of the air and the danger of breathing polluted air. Although emissions of harmful chemicals in the United States have reduced, thanks to the Clean Air Act, the American Lung Association claims that, as of 2024, 131 million Americans live in areas with unhealthy levels of air pollution.^[“2024 ‘State of the Air’ Report Reveals Most ‘Hazardous’ Air Quality Days in 25 Years.” American Lung Association, Saint Paul, United States. April 24, 2024. https://www.lung.org/media/press-releases/sota-2024.] This still-existent trend of more frequent and longer-lasting wildfires.^[Rickly, P. S et al.: “Emission factors and evolution of SO2 measured from biomass burning in wildfires and agricultural fires”, Atmos. *Chem. Phys., 22, 15603–15620*, https://doi.org/10.5194/acp-22-15603-2022, 2022.] This environmental trend prompts the necessity to create models so that we may be better prepared to handle worsening air quality in the future. With data on pollutants and certain demographic data, it should be possible to prepare for lockdowns based on air quality and predict the demand on hospital resources in a specific location.

# Data

The data to be used in this report is from a synthetic dataset created for Kaggle by Khushi Yadav, using a license from MIT. It is a time series spanning from the beginning of 2020 to the end of 2021. A large number of quantitative variables are included, such as AQI, industrial activity, and measures of the "six common pollutants" (PM$_{2.5}$, PM$_{10}$, O$_{3}$, CO, SO$_{2}$, and NO$_{2}$). Qualitative variables like the region and whether or not a lockdown has been issued are also included. Throughout this report, all variables in the dataset will be used in multiple contexts to create effective prediction models for future use.

Though the data may be synthetic, the results are still true to the real world–it was generated using public domain resources on realistic statistical distributions for accuracy, while protecting privacy by limiting real-world attachment to individual data points.

# The Appeal and Drawbacks of GLMs



# Introducing Machine Learning Models for Predictive Use



# Discussion


